/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnnotateRouteImport } from './routes/annotate'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BenchmarkingRouteImport } from './routes/benchmarking'
import { Route as FinetuningRouteImport } from './routes/finetuning'
import { Route as IngestionRouteImport } from './routes/ingestion'
import { Route as LabelProfileRouteImport } from './routes/label-profile'
import { Route as RlhfRouteImport } from './routes/rlhf'
import { Route as SyntheticDataRouteImport } from './routes/synthetic-data'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnotateRoute = AnnotateRouteImport.update({
  id: '/annotate',
  path: '/annotate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarkingRoute = BenchmarkingRouteImport.update({
  id: '/benchmarking',
  path: '/benchmarking',
  getParentRoute: () => rootRouteImport,
} as any)
const FinetuningRoute = FinetuningRouteImport.update({
  id: '/finetuning',
  path: '/finetuning',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestionRoute = IngestionRouteImport.update({
  id: '/ingestion',
  path: '/ingestion',
  getParentRoute: () => rootRouteImport,
} as any)
const LabelProfileRoute = LabelProfileRouteImport.update({
  id: '/label-profile',
  path: '/label-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RlhfRoute = RlhfRouteImport.update({
  id: '/rlhf',
  path: '/rlhf',
  getParentRoute: () => rootRouteImport,
} as any)
const SyntheticDataRoute = SyntheticDataRouteImport.update({
  id: '/synthetic-data',
  path: '/synthetic-data',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/annotate': typeof AnnotateRoute
  '/auth': typeof AuthRoute
  '/benchmarking': typeof BenchmarkingRoute
  '/finetuning': typeof FinetuningRoute
  '/ingestion': typeof IngestionRoute
  '/label-profile': typeof LabelProfileRoute
  '/rlhf': typeof RlhfRoute
  '/synthetic-data': typeof SyntheticDataRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/annotate': typeof AnnotateRoute
  '/auth': typeof AuthRoute
  '/benchmarking': typeof BenchmarkingRoute
  '/finetuning': typeof FinetuningRoute
  '/ingestion': typeof IngestionRoute
  '/label-profile': typeof LabelProfileRoute
  '/rlhf': typeof RlhfRoute
  '/synthetic-data': typeof SyntheticDataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/annotate': typeof AnnotateRoute
  '/auth': typeof AuthRoute
  '/benchmarking': typeof BenchmarkingRoute
  '/finetuning': typeof FinetuningRoute
  '/ingestion': typeof IngestionRoute
  '/label-profile': typeof LabelProfileRoute
  '/rlhf': typeof RlhfRoute
  '/synthetic-data': typeof SyntheticDataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/annotate'
    | '/auth'
    | '/benchmarking'
    | '/finetuning'
    | '/ingestion'
    | '/label-profile'
    | '/rlhf'
    | '/synthetic-data'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/annotate'
    | '/auth'
    | '/benchmarking'
    | '/finetuning'
    | '/ingestion'
    | '/label-profile'
    | '/rlhf'
    | '/synthetic-data'
  id:
    | '__root__'
    | '/'
    | '/annotate'
    | '/auth'
    | '/benchmarking'
    | '/finetuning'
    | '/ingestion'
    | '/label-profile'
    | '/rlhf'
    | '/synthetic-data'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnotateRoute: typeof AnnotateRoute
  AuthRoute: typeof AuthRoute
  BenchmarkingRoute: typeof BenchmarkingRoute
  FinetuningRoute: typeof FinetuningRoute
  IngestionRoute: typeof IngestionRoute
  LabelProfileRoute: typeof LabelProfileRoute
  RlhfRoute: typeof RlhfRoute
  SyntheticDataRoute: typeof SyntheticDataRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annotate': {
      id: '/annotate'
      path: '/annotate'
      fullPath: '/annotate'
      preLoaderRoute: typeof AnnotateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmarking': {
      id: '/benchmarking'
      path: '/benchmarking'
      fullPath: '/benchmarking'
      preLoaderRoute: typeof BenchmarkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finetuning': {
      id: '/finetuning'
      path: '/finetuning'
      fullPath: '/finetuning'
      preLoaderRoute: typeof FinetuningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingestion': {
      id: '/ingestion'
      path: '/ingestion'
      fullPath: '/ingestion'
      preLoaderRoute: typeof IngestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/label-profile': {
      id: '/label-profile'
      path: '/label-profile'
      fullPath: '/label-profile'
      preLoaderRoute: typeof LabelProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rlhf': {
      id: '/rlhf'
      path: '/rlhf'
      fullPath: '/rlhf'
      preLoaderRoute: typeof RlhfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/synthetic-data': {
      id: '/synthetic-data'
      path: '/synthetic-data'
      fullPath: '/synthetic-data'
      preLoaderRoute: typeof SyntheticDataRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnotateRoute: AnnotateRoute,
  AuthRoute: AuthRoute,
  BenchmarkingRoute: BenchmarkingRoute,
  FinetuningRoute: FinetuningRoute,
  IngestionRoute: IngestionRoute,
  LabelProfileRoute: LabelProfileRoute,
  RlhfRoute: RlhfRoute,
  SyntheticDataRoute: SyntheticDataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
